// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbEzoMa8m0KYJjX0Po66ZNAgGUflWg6M',
    appId: '1:723171376139:android:f911e343ffd04a6f949b0e',
    messagingSenderId: '723171376139',
    projectId: 'pipfa-13449',
    storageBucket: 'pipfa-13449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYdS3qYqaRbWGrP7btxCYcVmHae23vV8k',
    appId: '1:723171376139:ios:27afec6e4826edb6949b0e',
    messagingSenderId: '723171376139',
    projectId: 'pipfa-13449',
    storageBucket: 'pipfa-13449.firebasestorage.app',
    androidClientId: '723171376139-0vcv17mb9n35m2ki6k7dut3eqa1hf5eu.apps.googleusercontent.com',
    iosClientId: '723171376139-00p97odtv7jtdl7givlkb3css0ub9mct.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );
}
